"""
agents/response_agent.py — Automated response policy engine

Polls agent_queue for receiver='response_agent'.
Implements 3-tier policy + blast-radius rate limiter.

Policy:
  threat_score > 80  → BLOCK (if limiter allows, else downgrade to RATE_LIMIT)
  threat_score 50-80 → RATE_LIMIT
  threat_score < 50  → LOG_ONLY + increment escalation_score

All branches write full audit_log row with reasoning.
Updates incidents table.
Sends SMTP email for HIGH/CRITICAL (skips silently if no SMTP config).
All firewall calls go through prevention/firewall.py — never direct.
"""

import asyncio
import logging
import os
import smtplib
from datetime import datetime, timezone, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional

from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

AGENT_NAME    = "response_agent"
POLL_INTERVAL = 3   # seconds

# SMTP config (optional)
SMTP_HOST = os.getenv("SMTP_HOST", "")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587") or "587")
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")


# ── Email helper ──────────────────────────────────────────────────────────────

def _send_alert_email(ip: str, attack_type: str, verdict: str, threat_score: float, alert_id: str) -> None:
    """Send SMTP alert email. Silently skips if SMTP vars are not configured."""
    if not all([SMTP_HOST, SMTP_USER, SMTP_PASS]):
        return
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[IDS ALERT] {verdict} — {attack_type} from {ip}"
        msg["From"]    = SMTP_USER
        msg["To"]      = SMTP_USER   # Send to self; change as needed

        body = f"""
SECURITY ALERT — {verdict}

IP Address:   {ip}
Attack Type:  {attack_type}
Threat Score: {threat_score:.1f}/100
Alert ID:     {alert_id}
Timestamp:    {datetime.now(timezone.utc).isoformat()}

This alert was automatically generated by the IDS Agentic Response System.
"""
        msg.attach(MIMEText(body, "plain"))

        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, SMTP_USER, msg.as_string())

        logger.info("[response_agent] Alert email sent for %s.", ip)
    except Exception as e:
        logger.warning("[response_agent] SMTP send failed (non-critical): %s", e)


# ── Response actions ──────────────────────────────────────────────────────────

async def _execute_response(
    msg:      dict,
    payload:  dict,
    alert_id: Optional[str],
) -> None:
    from cloud_db import (
        update_queue_message, write_audit_log, update_agent_status,
        upsert_incident, add_to_blocklist
    )
    from prevention.firewall import block_ip, rate_limit_ip, get_rate_limiter
    from core.session_tracker import increment_escalation

    ip           = payload.get("ip", "")
    attack_type  = payload.get("attack_type", "UNKNOWN")
    threat_score = float(payload.get("threat_score", 50))
    verdict      = payload.get("verdict", "MEDIUM")
    recommended  = payload.get("recommended_action", "MONITOR")

    # Override threat_score with Gemini's if available
    inv_verdict  = payload.get("investigation_verdict", {}) or {}
    if inv_verdict.get("threat_score") is not None:
        threat_score = float(inv_verdict["threat_score"])

    limiter = get_rate_limiter()

    # ── 3-tier policy ─────────────────────────────────────────────────────────
    if threat_score > 80:
        if limiter.can_block():
            fw_result = block_ip(ip, alert_id=alert_id, reason=f"threat_score={threat_score:.0f}")
            limiter.record_block()
            action_taken = fw_result["action"]
            reasoning = (
                f"threat_score={threat_score:.1f} > 80 threshold. "
                f"Firewall action: {action_taken}. "
                f"Mock={fw_result.get('mock', False)}."
            )
            # Add to blocklist cache
            add_to_blocklist(ip, source="response_agent", score=threat_score)

            # Email for HIGH/CRITICAL
            if verdict in ("HIGH", "CRITICAL"):
                _send_alert_email(ip, attack_type, verdict, threat_score, alert_id or "")
        else:
            # Rate limiter saturated — downgrade
            fw_result = rate_limit_ip(ip, alert_id=alert_id, reason="blast_radius_limit_reached")
            action_taken = fw_result["action"] + "_DOWNGRADED"
            reasoning = (
                f"threat_score={threat_score:.1f} > 80 but blast-radius limiter saturated "
                f"(limit={limiter.stats()}). Downgraded to rate-limit."
            )
    elif threat_score >= 50:
        fw_result    = rate_limit_ip(ip, alert_id=alert_id, reason=f"threat_score={threat_score:.0f}")
        action_taken = fw_result["action"]
        reasoning = (
            f"threat_score={threat_score:.1f} in 50-80 range → rate-limit. "
            f"Mock={fw_result.get('mock', False)}."
        )
    else:
        action_taken = "LOG_ONLY"
        reasoning = (
            f"threat_score={threat_score:.1f} < 50 → log only, "
            f"incrementing escalation score for {ip}."
        )
        increment_escalation(ip, delta=threat_score * 0.1)

    # ── Upsert incident with enriched data ────────────────────────────────────
    try:
        upsert_incident({
            "src_ip":          ip,
            "attack_type":     attack_type,
            "timestamp":       datetime.now(timezone.utc).isoformat(),
            "outcome":         payload.get("outcome", "ATTEMPT"),
            "confidence":      payload.get("confidence", 50),
            "severity":        payload.get("severity", "MEDIUM"),
            "mitre_tags":      payload.get("mitre_tags", []),
            "kill_chain_phase": payload.get("kill_chain_phase"),
            "threat_score":    threat_score,
        })
    except Exception as e:
        logger.error("[response_agent] incident upsert failed: %s", e)

    # ── Write audit log ───────────────────────────────────────────────────────
    write_audit_log(
        agent     = AGENT_NAME,
        action    = action_taken,
        reasoning = reasoning,
        metadata  = {
            "ip":           ip,
            "attack_type":  attack_type,
            "threat_score": threat_score,
            "verdict":      verdict,
            "limiter_stats": limiter.stats(),
        },
        alert_id  = alert_id,
    )

    update_queue_message(msg["id"], {"status": "DONE"})

    logger.warning(
        "[response_agent] ip=%s attack=%s threat=%.1f action=%s",
        ip, attack_type, threat_score, action_taken,
    )


# ── Main poll loop ────────────────────────────────────────────────────────────

async def run_forever() -> None:
    from cloud_db import get_pending_queue_messages, update_agent_status
    update_agent_status(AGENT_NAME, "IDLE")
    logger.info("[response_agent] started, polling every %ds.", POLL_INTERVAL)

    while True:
        try:
            messages = get_pending_queue_messages(AGENT_NAME, limit=5)
            for msg in messages:
                from cloud_db import update_agent_status
                update_agent_status(AGENT_NAME, "BUSY", msg.get("alert_id"))
                await _execute_response(msg, msg.get("payload", {}), msg.get("alert_id"))
                update_agent_status(AGENT_NAME, "IDLE")
        except Exception as e:
            logger.error("[response_agent] poll error: %s", e)

        await asyncio.sleep(POLL_INTERVAL)
